# code: language=dockercompose
volumes:
  vlstorage: {}
  grafana: {}
services:
  victoria-logs:
    image: victoriametrics/victoria-logs:v1.8.0-victorialogs
    volumes:
      - vlstorage:/vlstorage
    command:
      - --storageDataPath=/vlstorage
      - --retentionPeriod=100d
      - --syslog.listenAddr.udp=:5514
      - --syslog.listenAddr.tcp=:5514
      - --syslog.streamFields.tcp='["hostname","app_name","priority","facility","severity"]'
      - --syslog.streamFields.udp='["hostname","app_name","priority","facility","severity"]'
    ports:
      - 9428:9428
      - 5514:5514
      - 5514:5514/udp
    restart: always
    deploy:
      mode: global
  grafana:
    image: grafana/grafana:11.5.1
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: always
    environment:
      - GF_INSTALL_PLUGINS=victoriametrics-logs-datasource,yesoreyeram-infinity-datasource
      - GF_SECURITY_ADMIN_PASSWORD=SuperSecret
  geoip-service:
    restart: always
    ports:
      - 5555:5555
    build: ./geoip-service
    deploy:
      mode: global
