{
 "title": "Mikrotik Loki Logs Country",
 "description": "Mikrotik Loki Logs",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Incoming connections",
   "type": "logs",
   "gridPos": { "h": 17, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"MikroTik\"} |= \"dnat\" | pattern `<_> src-mac <_>, proto <_>, <src_ip>:<src_port>-><dst_ip>:<dst_port>, <_>`\n| line_format \"{{.src_ip}}: Country:{{.geoip_country_name}}, City:{{.geoip_city_name}} \" ",
     "maxLines": 50
    }
   ]
  },
  {
   "title": "Incoming connections by country",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": " count by(geoip_country_name) (rate({host=\"MikroTik\"} |= `dnat` [$__auto] ) ) "
    }
   ]
  },
  {
   "title": "All incoming connection",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"MikroTik\"} |= \"dnat\" ",
     "maxLines": 50
    }
   ]
  }
 ]
}