{
 "title": "Mikrotik VM Logs",
 "tags": [
  "victorialogs",
  "mikrotik"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "last_messages_number",
    "label": "Number of last messages in top graphs",
    "query": "10"
   }
  ]
 },
 "panels": [
  {
   "title": "All NAT logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "snat OR dnat | count()" }
   ]
  },
  {
   "title": "All snat logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "snat | count()" }
   ]
  },
  {
   "title": "All dnat logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "dnat | count()" }
   ]
  },
  {
   "title": "Top $last_messages_number in connections by IP",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnat | extract \", proto <proto>, <src-ip>:<src-port>-><dst-ip>:<dst-port>, NAT\" from _msg | stats by (src-ip) count() src-ip-count | sort (src-ip-count) desc limit $last_messages_number"
    }
   ]
  },
  {
   "title": "Top $last_messages_number in connections by ports",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnat | extract \", proto <proto>, <src-ip>:<src-port>-><dst-ip>:<dst-port>, NAT\" from _msg | stats by (dst-port) count() dst-port-count | sort (dst-port-count) desc limit $last_messages_number"
    }
   ]
  },
  {
   "title": "Top $last_messages_number out connections by IP",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snat | extract \", proto <proto>, <src-ip>:<src-port>-><dst-ip>:<dst-port>, NAT\" from _msg | stats by (dst-ip) count() dst-ip-count | sort (dst-ip-count) desc limit $last_messages_number"
    }
   ]
  },
  {
   "title": "Top $last_messages_number out connections by port",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snat | extract \", proto <proto>, <src-ip>:<src-port>-><dst-ip>:<dst-port>, NAT\" from _msg | stats by (dst-port) count() dst-port-count | sort (dst-port-count) desc limit $last_messages_number"
    }
   ]
  },
  {
   "title": "Incoming connections",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "dnat | extract \", proto <proto>, <src-ip>:<src-port>-><dst-ip-port>, NAT <nat>\" from _msg | format \"⚠️ New connection from <src-ip>:<src-port> to <dst-ip-port>, proto: <proto>\" | limit 30"
    }
   ]
  },
  {
   "title": "Outgoing connection",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "snat | extract \", proto <proto>, <src-ip>:<src-port>-><dst-ip-port>, NAT <nat>\" from _msg | format \"⚠️ New connection from <src-ip>:<src-port> to <dst-ip-port>, proto <proto>\" | limit 30"
    }
   ]
  },
  {
   "title": "All connections",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "targets": [
    { "expr": "*" }
   ]
  }
 ]
}